/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004493",
        "surface-container-low": "#1b1c1d",
        "on-tertiary": "#003730",
        "secondary": "#4edea3",
        "on-surface-variant": "#c1c6d7",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#00302a",
        "tertiary-container": "#00a391",
        "tertiary-fixed": "#6ef9e2",
        "soft-graphite": "#1C212C",
        "surface-bright": "#38393a",
        "on-secondary": "#003824",
        "frost-white": "#F8FAFC",
        "error-container": "#93000a",
        "outline-variant": "#414755",
        "on-error-container": "#ffdad6",
        "tertiary": "#4ddcc6",
        "electric-blue": "#2E90FA",
        "surface-container-highest": "#343536",
        "on-error": "#690005",
        "on-primary": "#002e69",
        "surface-dim": "#121315",
        "tertiary-fixed-dim": "#4ddcc6",
        "on-primary-container": "#00285c",
        "deep-navy": "#0A0F1D",
        "primary": "#adc6ff",
        "on-primary-fixed": "#001a41",
        "surface-container-high": "#292a2b",
        "on-secondary-fixed": "#002113",
        "on-background": "#e3e2e3",
        "secondary-fixed": "#6ffbbe",
        "cyan-glow": "#00F0FF",
        "emerald-highlight": "#10B981",
        "surface": "#121315",
        "inverse-surface": "#e3e2e3",
        "surface-container-lowest": "#0d0e0f",
        "on-secondary-container": "#00311f",
        "secondary-container": "#00a572",
        "outline": "#8b90a0",
        "on-tertiary-fixed-variant": "#005047",
        "surface-variant": "#343536",
        "inverse-primary": "#005bc1",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#1f2021",
        "on-tertiary-fixed": "#00201b",
        "background": "#121315",
        "primary-fixed-dim": "#adc6ff",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#303032",
        "primary-container": "#4b8eff",
        "on-surface": "#e3e2e3",
        "surface-tint": "#adc6ff"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "stats-xl": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "stats-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      },
      spacing: {
        "grid-margin": "48px",
        "unit": "8px",
        "container-max": "1440px",
        "grid-gutter": "24px"
      },
      borderRadius: {
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
    },
  },
  plugins: [],
}
